channels:
    - defaults
    - conda-forge
    - microsoft
dependencies:
    - python=3.11.3
    - pip
    - pytest=7.1.2
    - nodejs=16
    - black
    - isort
    - codespell
    - pre-commit
    - pillow
    - numpy
    - markdown
    - toml
    - pip:
          - playwright==1.33.0
          - pytest-playwright==0.3.3
          - pytest-xdist==3.3.0
          # We need Pyodide and micropip so we can import them in our Python
          # unit tests
          - pyodide_py==0.22
          - micropip==0.2.2
