channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip=20.2.2
  - Sphinx=4.5.0
  - myst-parser=0.17.2
  - pydata-sphinx-theme
  - sphinx-copybutton
  - sphinx-panels
  - sphinx-togglebutton
  - pip:
    - sphinxemoji
    - sphinx-sitemap
