name: "[CI] Sync Examples"

on:
    push: # Only run on merges into master that modify files under pyscriptjs/
        branches:
        -   main
        paths:
        -   pyscriptjs/examples/**
        -   .github/workflows/sync-examples.yml # Test that workflow works when changed

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        defaults:
            run:
                working-directory: ./pyscriptjs/examples

        steps:
        # Deploy to S3
        -   name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1.6.1
            with:
                aws-region: ${{secrets.AWS_REGION}}
                role-to-assume: ${{ secrets.AWS_OIDC_RUNNER_ROLE }}
        -   name: Sync to S3
            run: aws s3 sync . s3://pyscript-static/examples/
